## Cargar los datos ##

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('data/features_3_sec.csv', skipinitialspace=True)

# eliminar filas que no tienen género
df = df.dropna(subset=['label']) 

#feature que queremos predecir
y = df['label'] 

#features para el entrenamiento
X = df.drop(columns=["label"]).copy()

# Convertir columnas binarias de texto en 0 y 1
text_columns = X.select_dtypes(include=['str', 'object', 'string']).columns

for col in text_columns:
    values = X[col].dropna().unique()

    if len(values) == 2:
        X[col] = X[col].map({
            values[0]: 0,
            values[1]: 1})
            
#asegurar que solo hay valores numéricos
X = X.select_dtypes(include=np.number)

print("Número de canciones:", len(df))
print("Número de features:", X.shape[1])
print("\nCanciones por género:")
print(y.value_counts())

df.head()

Número de canciones: 9990
Número de features: 58

Canciones por género:
label
blues        1000
jazz         1000
metal        1000
pop          1000
reggae       1000
disco         999
classical     998
hiphop        998
rock          998
country       997
Name: count, dtype: int64

,filename,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,blues.00000.0.wav,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,...,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,blues
1,blues.00000.1.wav,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,...,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,blues
2,blues.00000.2.wav,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,...,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,blues
3,blues.00000.3.wav,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,...,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,blues
4,blues.00000.4.wav,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,...,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,blues

## Definición de los modelos ##

Un pipeline es una cadena de pasos que se ejecutan en orden. Por ejemplo, antes de entrenar un modelo, podemos necesitar rellenar datos que faltan y normalizar las características.

`Pipeline` permite crear un pipeline combinando varios pasos

`SimpleImputer` sirve para rellenar los valores que faltan en los datos, por ejemplo, cuando una característica musical contiene NaN. se puede usar `StandardScaler` para rellenar esos datos vacíos

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

#modelos
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

In [6]:
models = {
    "Logistic Regression": (
        Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(max_iter=2000))
        ]),
        {
            "model__C": [0.01, 0.03, 0.1, 0.3, 1]
        }
    ),

    "k-NN": (
        Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", KNeighborsClassifier())
        ]),
        {
            "model__n_neighbors": [3, 5, 7, 9, 13, 17],
            "model__weights": ["uniform", "distance"],
            "model__p": [1, 2]
        }
    ),

    "Decision Tree": (
        Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", DecisionTreeClassifier(random_state=42))
        ]),
        {
            "model__max_depth": [5, 10, 15],
            "model__min_samples_split": [5, 10],
            "model__min_samples_leaf": [5, 10]
        }
    ),

    "Artificial Neural Network": (
        Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                max_iter=500,
                random_state=42,
                early_stopping=False,
                n_iter_no_change=15,
                tol=1e-3
            ))
        ]),
        {
            "model__hidden_layer_sizes": [(30,), (50,), (100,), (50, 25)],
            "model__alpha": [0.01, 0.1, 1.0]
        }
    )
}

## Definir la validación cruzada
 
Mismo esquema de 10 folds para comparar todos los algoritmos

In [7]:
from sklearn.model_selection import StratifiedKFold

In [8]:
cv = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42)

## Entrenar y evaluar los modelos

Esta es la celda principal. `GridSearchCV` probará todas las configuraciones usando validación cruzada de 10 folds y seleccionará la que obtenga la mejor accuracy media para cada algoritmo

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:

results = []
best_models = {}

for name, (pipeline, params) in models.items():

    print("\nEvaluando:", name)

    search = GridSearchCV(
        estimator=pipeline,
        param_grid=params,
        scoring="accuracy",
        cv=cv,
        return_train_score=True,
        n_jobs=-1)

    search.fit(X, y)

    best_models[name] = search

    # Guardar los resultados de todas las configuraciones
    for i in range(len(search.cv_results_["params"])):
        results.append({
            "Algorithm": name,
            "Parameters": search.cv_results_["params"][i],
            "Train accuracy": search.cv_results_["mean_train_score"][i],
            "CV accuracy": search.cv_results_["mean_test_score"][i]})

    # Seleccionar la configuración con mayor accuracy
    # entre las que tienen overfitting < 0.15
    cv_results = pd.DataFrame(search.cv_results_)

    cv_results["Overfitting gap"] = (cv_results["mean_train_score"] - cv_results["mean_test_score"])

    valid_results = cv_results[cv_results["Overfitting gap"] < 0.15]

    #si no se alcanza el objetivo de ovefitting menor que 0,15, busca el que más ccuracy tenga directamente
    if not valid_results.empty:
        best_row = valid_results.sort_values("mean_test_score", ascending=False).iloc[0]
    else:
        best_row = cv_results.sort_values("mean_test_score", ascending=False).iloc[0]

    print("Best parameters:", best_row["params"])
    print("Best 10-fold CV accuracy (without overfitting):", round(best_row["mean_test_score"], 4))
    print("Overfitting gap:", round(best_row["Overfitting gap"], 4))
    print("Overfitting ok:", best_row["Overfitting gap"] < 0.15)


results_df = pd.DataFrame(results)

results_df["Overfitting gap"] = (
    results_df["Train accuracy"] -
    results_df["CV accuracy"]
)

results_df["Acceptable accuracy"] = (
    (results_df["CV accuracy"] > 0.70) 
)

results_df["Acceptable overfitting"] = (
    results_df["Overfitting gap"] < 0.15
)
results_df["Fits objectives"] = (
    (results_df["Overfitting gap"] < 0.15) & 
    (results_df["CV accuracy"] > 0.70)
)

results_df = results_df.sort_values(
    ["Acceptable overfitting", "CV accuracy", "Overfitting gap"],
    ascending=[False, False, True]
).reset_index(drop=True)

print(f"Total configs evaluated: {len(results_df)}")
print(f"Configs with appropiate overfitting: "
      f"{results_df['Acceptable overfitting'].sum()}")
print(f"Configs with both good accuracy and overfitting: "
      f"{results_df['Fits objectives'].sum()}")

display(results_df)

Evaluando: Logistic Regression
Best parameters: {'model__C': 1}
Best 10-fold CV accuracy (without overfitting): 0.7242
Overfitting gap: 0.0186
Overfitting ok: True

Evaluando: k-NN
Best parameters: {'model__n_neighbors': 3, 'model__p': 1, 'model__weights': 'distance'}
Best 10-fold CV accuracy (without overfitting): 0.9349
Overfitting gap: 0.0642
Overfitting ok: True

Evaluando: Decision Tree
Best parameters: {'model__max_depth': 15, 'model__min_samples_leaf': 10, 'model__min_samples_split': 10}
Best 10-fold CV accuracy (without overfitting): 0.6342
Overfitting gap: 0.1482
Overfitting ok: True

Evaluando: Artificial Neural Network
Best parameters: {'model__alpha': 0.1, 'model__hidden_layer_sizes': (100,)}
Best 10-fold CV accuracy (without overfitting): 0.8886
Overfitting gap: 0.1022
Overfitting ok: True
Total configs evaluated: 53
Configs with appropiate overfitting: 50
Configs with both good accuracy and overfitting: 39

,Algorithm,Parameters,Train accuracy,CV accuracy,Overfitting gap,Acceptable accuracy,Acceptable overfitting,Fits objectives
0,k-NN,"{'model__n_neighbors': 3, 'model__p': 1, 'mode...",0.999110,0.934935,0.064175,True,True,True
1,k-NN,"{'model__n_neighbors': 3, 'model__p': 1, 'mode...",0.970393,0.928529,0.041864,True,True,True
2,k-NN,"{'model__n_neighbors': 5, 'model__p': 1, 'mode...",0.999110,0.926727,0.072383,True,True,True
3,k-NN,"{'model__n_neighbors': 7, 'model__p': 1, 'mode...",0.999110,0.919319,0.079791,True,True,True
4,k-NN,"{'model__n_neighbors': 5, 'model__p': 1, 'mode...",0.957235,0.917117,0.040118,True,True,True
5,k-NN,"{'model__n_neighbors': 9, 'model__p': 1, 'mode...",0.999110,0.915516,0.083595,True,True,True
6,k-NN,"{'model__n_neighbors': 3, 'model__p': 2, 'mode...",0.999110,0.913113,0.085997,True,True,True
7,k-NN,"{'model__n_neighbors': 7, 'model__p': 1, 'mode...",0.943721,0.910310,0.033411,True,True,True
8,k-NN,"{'model__n_neighbors': 5, 'model__p': 2, 'mode...",0.999110,0.907708,0.091403,True,True,True
9,k-NN,"{'model__n_neighbors': 9, 'model__p': 1, 'mode...",0.932232,0.902603,0.029630,True,True,True
10,k-NN,"{'model__n_neighbors': 3, 'model__p': 2, 'mode...",0.959193,0.902102,0.057090,True,True,True
11,k-NN,"{'model__n_neighbors': 13, 'model__p': 1, 'mod...",0.999110,0.900400,0.098710,True,True,True
12,k-NN,"{'model__n_neighbors': 7, 'model__p': 2, 'mode...",0.999110,0.899900,0.099210,True,True,True
13,k-NN,"{'model__n_neighbors': 5, 'model__p': 2, 'mode...",0.940607,0.893193,0.047414,True,True,True
14,k-NN,"{'model__n_neighbors': 9, 'model__p': 2, 'mode...",0.999110,0.890691,0.108420,True,True,True
15,Artificial Neural Network,"{'model__alpha': 0.1, 'model__hidden_layer_siz...",0.990757,0.888589,0.102169,True,True,True
16,k-NN,"{'model__n_neighbors': 7, 'model__p': 2, 'mode...",0.925759,0.887387,0.038372,True,True,True
17,k-NN,"{'model__n_neighbors': 17, 'model__p': 1, 'mod...",0.999110,0.886887,0.112223,True,True,True
18,Artificial Neural Network,"{'model__alpha': 0.01, 'model__hidden_layer_si...",0.998054,0.883984,0.114070,True,True,True
19,k-NN,"{'model__n_neighbors': 13, 'model__p': 1, 'mod...",0.913780,0.882182,0.031598,True,True,True
20,k-NN,"{'model__n_neighbors': 13, 'model__p': 2, 'mod...",0.999110,0.878078,0.121032,True,True,True
21,k-NN,"{'model__n_neighbors': 9, 'model__p': 2, 'mode...",0.913625,0.877277,0.036347,True,True,True
22,k-NN,"{'model__n_neighbors': 17, 'model__p': 1, 'mod...",0.894606,0.863163,0.031443,True,True,True
23,k-NN,"{'model__n_neighbors': 17, 'model__p': 2, 'mod...",0.999110,0.863063,0.136047,True,True,True
24,k-NN,"{'model__n_neighbors': 13, 'model__p': 2, 'mod...",0.892559,0.857958,0.034601,True,True,True
25,Artificial Neural Network,"{'model__alpha': 0.1, 'model__hidden_layer_siz...",0.959170,0.856356,0.102814,True,True,True
26,Artificial Neural Network,"{'model__alpha': 1.0, 'model__hidden_layer_siz...",0.927739,0.853153,0.074586,True,True,True
27,Artificial Neural Network,"{'model__alpha': 0.01, 'model__hidden_layer_si...",0.977188,0.851351,0.125837,True,True,True
28,Artificial Neural Network,"{'model__alpha': 0.1, 'model__hidden_layer_siz...",0.992181,0.849650,0.142531,True,True,True
29,Artificial Neural Network,"{'model__alpha': 1.0, 'model__hidden_layer_siz...",0.898866,0.844545,0.054321,True,True,True
30,k-NN,"{'model__n_neighbors': 17, 'model__p': 2, 'mod...",0.872706,0.840140,0.032566,True,True,True
31,Artificial Neural Network,"{'model__alpha': 0.1, 'model__hidden_layer_siz...",0.895584,0.819419,0.076165,True,True,True
32,Artificial Neural Network,"{'model__alpha': 1.0, 'model__hidden_layer_siz...",0.868035,0.819319,0.048715,True,True,True
33,Artificial Neural Network,"{'model__alpha': 0.01, 'model__hidden_layer_si...",0.907051,0.818118,0.088933,True,True,True
34,Artificial Neural Network,"{'model__alpha': 1.0, 'model__hidden_layer_siz...",0.836270,0.797397,0.038872,True,True,True
35,Logistic Regression,{'model__C': 1},0.742809,0.724224,0.018585,True,True,True
36,Logistic Regression,{'model__C': 0.3},0.739473,0.721321,0.018151,True,True,True
37,Logistic Regression,{'model__C': 0.1},0.734902,0.718619,0.016283,True,True,True
38,Logistic Regression,{'model__C': 0.03},0.723101,0.709309,0.013792,True,True,True
39,Logistic Regression,{'model__C': 0.01},0.704705,0.693193,0.011512,False,True,False
40,Decision Tree,"{'model__max_depth': 15, 'model__min_samples_l...",0.782394,0.634234,0.148159,False,True,False
41,Decision Tree,"{'model__max_depth': 15, 'model__min_samples_l...",0.782394,0.634234,0.148159,False,True,False
42,Decision Tree,"{'model__max_depth': 10, 'model__min_samples_l...",0.718151,0.611912,0.106240,False,True,False
43,Decision Tree,"{'model__max_depth': 10, 'model__min_samples_l...",0.718151,0.611912,0.106240,False,True,False
44,Decision Tree,"{'model__max_depth': 10, 'model__min_samples_l...",0.698020,0.604505,0.093516,False,True,False
45,Decision Tree,"{'model__max_depth': 10, 'model__min_samples_l...",0.698020,0.604505,0.093516,False,True,False
46,Decision Tree,"{'model__max_depth': 5, 'model__min_samples_le...",0.456045,0.438939,0.017106,False,True,False
47,Decision Tree,"{'model__max_depth': 5, 'model__min_samples_le...",0.456045,0.438939,0.017106,False,True,False
48,Decision Tree,"{'model__max_depth': 5, 'model__min_samples_le...",0.454922,0.438138,0.016783,False,True,False
49,Decision Tree,"{'model__max_depth': 5, 'model__min_samples_le...",0.454922,0.438138,0.016783,False,True,False
50,Artificial Neural Network,"{'model__alpha': 0.01, 'model__hidden_layer_si...",0.998343,0.844945,0.153398,True,False,False
51,Decision Tree,"{'model__max_depth': 15, 'model__min_samples_l...",0.848081,0.653854,0.194228,False,False,False
52,Decision Tree,"{'model__max_depth': 15, 'model__min_samples_l...",0.848081,0.653854,0.194228,False,False,False